# Generated by Django 5.2.7 on 2026-04-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowa_settings', '0002_companysettings_address_companysettings_email_and_more'),
        ('tenancy', '0013_company_currency_locked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='currency',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='tenancy.company'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'company')},
        ),
    ]
