# Generated by Django 5.2.7 on 2025-11-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcustomer',
            name='actions',
        ),
    ]
