# Generated by Django 5.2.7 on 2025-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0002_remove_newcustomer_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
