# Generated by Django 5.2.7 on 2025-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0003_newcustomer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
