# Generated by Django 5.2.7 on 2025-12-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
