# Generated by Django 5.2.7 on 2025-12-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0005_alter_newcustomer_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
