# Generated by Django 5.2.7 on 2025-12-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0007_alter_newcustomer_opening_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupplier',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsupplier',
            name='tax_rate',
        ),
    ]
