# Generated by Django 5.2.7 on 2025-12-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('sowaf', '0008_remove_newsupplier_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupplier',
            name='ap_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ap_owner', to='accounts.account'),
        ),
    ]
