# Generated by Django 5.2.7 on 2025-12-25 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('sowaf', '0009_newsupplier_ap_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='ar_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ar_owner', to='accounts.account'),
        ),
    ]
