# Generated by Django 5.2.7 on 2026-02-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('sowaf', '0010_newcustomer_ar_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='newasset',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Bank/Cash account used to pay for the asset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_payments', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='asset_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'NON_CURRENT_ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='asset_attachments',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disposed', 'Disposed'), ('Written-Off', 'Written-Off')], default='Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='capitalization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('Straight line', 'Straight line'), ('Reducing balance', 'Reducing balance')], default='Straight line', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
