# Generated by Django 5.2.7 on 2026-02-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0011_newasset_payment_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newclient',
        ),
    ]
