# Generated by Django 5.2.7 on 2026-02-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0012_delete_newclient'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=255)),
                ('company_country', models.CharField(max_length=100)),
                ('business_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('business_start_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_position', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('industry', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('selected_package', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('bill_to', models.CharField(default='firm', max_length=20)),
                ('primary_admin', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenancy.company')),
            ],
        ),
    ]
