# Generated by Django 5.2.7 on 2026-02-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0014_newcustomer_company'),
        ('tenancy', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='tenancy.company'),
        ),
    ]
