# Generated by Django 5.2.7 on 2026-02-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0015_alter_client_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
