# Generated by Django 5.2.7 on 2026-03-11 11:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_company_alter_columnpreference_company_and_more'),
        ('sowaf', '0016_delete_client'),
        ('tenancy', '0009_company_company_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newemployee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='newasset',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newemployee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsupplier',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newasset',
            name='accumulated_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='remaining_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='residual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_assets', to='sowaf.newsupplier'),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='doc_attachments',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='intaxable_allowances',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='taxable_allowances',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='open_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='newasset',
            index=models.Index(fields=['company', 'asset_name'], name='sowaf_newas_company_e373ba_idx'),
        ),
        migrations.AddIndex(
            model_name='newasset',
            index=models.Index(fields=['company', 'asset_tag'], name='sowaf_newas_company_cc99da_idx'),
        ),
        migrations.AddIndex(
            model_name='newasset',
            index=models.Index(fields=['company', 'asset_status'], name='sowaf_newas_company_8bb7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='newcustomer',
            index=models.Index(fields=['company', 'customer_name'], name='sowaf_newcu_company_0a9609_idx'),
        ),
        migrations.AddIndex(
            model_name='newcustomer',
            index=models.Index(fields=['company', 'company_name'], name='sowaf_newcu_company_151efc_idx'),
        ),
        migrations.AddIndex(
            model_name='newcustomer',
            index=models.Index(fields=['company', 'is_active'], name='sowaf_newcu_company_ff58a2_idx'),
        ),
        migrations.AddIndex(
            model_name='newemployee',
            index=models.Index(fields=['company', 'first_name'], name='sowaf_newem_company_c0e84d_idx'),
        ),
        migrations.AddIndex(
            model_name='newemployee',
            index=models.Index(fields=['company', 'last_name'], name='sowaf_newem_company_fa261b_idx'),
        ),
        migrations.AddIndex(
            model_name='newemployee',
            index=models.Index(fields=['company', 'status'], name='sowaf_newem_company_f01f55_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupplier',
            index=models.Index(fields=['company', 'company_name'], name='sowaf_newsu_company_078e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupplier',
            index=models.Index(fields=['company', 'supplier_type'], name='sowaf_newsu_company_ecec35_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupplier',
            index=models.Index(fields=['company', 'is_active'], name='sowaf_newsu_company_c24020_idx'),
        ),
    ]
