# Generated by Django 5.2.7 on 2026-03-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0017_alter_newemployee_options_newasset_company_and_more'),
        ('tenancy', '0010_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newasset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='newsupplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
    ]
