# Generated by Django 5.2.7 on 2025-11-05 08:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('preferences', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('card', 'Card')], default='cash', max_length=40)),
                ('ref_no', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='expense_attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_billable', models.BooleanField(default=False)),
                ('bill_status', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed')], default='unbilled', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_billable', models.BooleanField(default=False)),
                ('bill_status', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed')], default='unbilled', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bill_no', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='BillCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lines', to='expenses.bill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='BillItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='expenses.bill')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('mailing_address', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('cheque_no', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_payments', to='accounts.account')),
                ('payee_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChequeCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lines', to='expenses.cheque')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='expenses.cheque')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
