# Generated by Django 5.2.7 on 2025-12-03 21:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentry_source_app'),
        ('expenses', '0003_purchaseorder_purchaseorderline'),
        ('inventory', '0002_alter_product_expense_account_and_more'),
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('mailing_address', models.CharField(blank=True, max_length=255)),
                ('credit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('ref_no', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credits', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ('-credit_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
                ('supplier_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.suppliercredit')),
            ],
        ),
    ]
