# Generated by Django 5.2.7 on 2025-12-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_suppliercredit_suppliercreditline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercredit',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercreditline',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
