# Generated by Django 5.2.7 on 2025-12-04 08:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentry_source_app'),
        ('expenses', '0005_alter_suppliercredit_location_and_more'),
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDownCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ref_no', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paydown_bank_accounts', to='accounts.account')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_paydowns', to='accounts.account')),
                ('payee_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
    ]
