# Generated by Django 5.2.7 on 2025-12-04 15:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentry_source_app'),
        ('expenses', '0006_paydowncredit'),
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('credit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('ref_no', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(help_text='The credit card account this credit applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_credits', to='accounts.account')),
                ('payee_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_credits', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ('-credit_date', '-id'),
            },
        ),
    ]
