# Generated by Django 5.2.7 on 2025-12-04 15:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentry_source_app'),
        ('expenses', '0007_creditcardcredit'),
        ('inventory', '0002_alter_product_expense_account_and_more'),
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardcredit',
            name='payee_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_credits', to='sowaf.newsupplier'),
        ),
        migrations.AlterField(
            model_name='paydowncredit',
            name='payee_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier'),
        ),
        migrations.CreateModel(
            name='CreditCardCreditCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('billable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_credit_category_lines', to='accounts.account')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lines', to='expenses.creditcardcredit')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_credit_category_lines', to='sowaf.newcustomer')),
                ('pclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_credit_category_lines', to='inventory.pclass')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardCreditItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('billable', models.BooleanField(default=False)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='expenses.creditcardcredit')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_credit_item_lines', to='sowaf.newcustomer')),
                ('pclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_credit_item_lines', to='inventory.pclass')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_credit_item_lines', to='inventory.product')),
            ],
        ),
    ]
