# Generated by Django 5.2.7 on 2025-12-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_audittrail_new_data_alter_audittrail_old_data'),
        ('expenses', '0008_alter_creditcardcredit_payee_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_source', to='accounts.journalentry'),
        ),
    ]
