# Generated by Django 5.2.7 on 2025-12-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_audittrail_new_data_alter_audittrail_old_data'),
        ('expenses', '0009_bill_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_source', to='accounts.journalentry'),
        ),
    ]
