# Generated by Django 5.2.7 on 2025-12-27 12:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_bill_journal_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_bill_lines', to='expenses.bill')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_lines', to='expenses.cheque')),
            ],
            options={
                'unique_together': {('cheque', 'bill')},
            },
        ),
    ]
