# Generated by Django 5.2.7 on 2025-12-28 17:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_chequebillline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeOpenBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cheque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_balance_line', to='expenses.cheque')),
            ],
        ),
    ]
