# Generated by Django 5.2.7 on 2026-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_expense_is_posted_expense_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
