# Generated by Django 5.2.7 on 2026-02-19 07:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_bill_is_posted_bill_posted_at'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
