# Generated by Django 5.2.7 on 2026-02-19 07:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_location_data(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    InventoryLocation = apps.get_model("inventory", "InventoryLocation")

    valid_locations = {str(obj.pk): obj.pk for obj in InventoryLocation.objects.all()}

    for expense in Expense.objects.all():
        old_value = getattr(expense, "location_old", None)

        if old_value is None:
            continue

        old_value = str(old_value).strip()

        if not old_value:
            continue

        if old_value in valid_locations:
            expense.location = valid_locations[old_value]
            expense.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_bill_is_posted_bill_posted_at'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='location',
            new_name='location_old',
        ),
        migrations.AddField(
            model_name='expense',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expenses',
                to='inventory.inventorylocation',
            ),
        ),
        migrations.RunPython(copy_location_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expense',
            name='location_old',
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=14,
            ),
        ),
    ]