# Generated by Django 5.2.7 on 2026-02-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expense_location_alter_expense_total_amount'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.inventorylocation'),
        ),
    ]
