# Generated by Django 5.2.7 on 2026-03-04 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_company_alter_columnpreference_company_and_more'),
        ('expenses', '0017_alter_bill_location_alter_cheque_location_and_more'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
        ('sowaf', '0016_delete_client'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-payment_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='creditcardcredit',
            options={'ordering': ['-credit_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='paydowncredit',
            options={'ordering': ['-payment_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-po_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='suppliercredit',
            options={'ordering': ['-credit_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='supplierrefund',
            options={'ordering': ['-refund_date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardcredit',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paydowncredit',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcardcredit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_card_credits', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='paydowncredit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paydown_credits', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='supplierrefund',
            name='received_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refund_received_to', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together={('company', 'user', 'table_name')},
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'bill_date'], name='expenses_bi_company_58486c_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'supplier'], name='expenses_bi_company_e1a758_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['company', 'payment_date'], name='expenses_ch_company_451393_idx'),
        ),
        migrations.AddIndex(
            model_name='columnpreference',
            index=models.Index(fields=['company', 'user', 'table_name'], name='expenses_co_company_c7e78e_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardcredit',
            index=models.Index(fields=['company', 'credit_date'], name='expenses_cr_company_be193f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'payment_date'], name='expenses_ex_company_1a6129_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'is_posted'], name='expenses_ex_company_d53c35_idx'),
        ),
        migrations.AddIndex(
            model_name='paydowncredit',
            index=models.Index(fields=['company', 'payment_date'], name='expenses_pa_company_dd3b67_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'po_date'], name='expenses_pu_company_ddf4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['company', 'credit_date'], name='expenses_su_company_544150_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['company', 'refund_date'], name='expenses_su_company_6936b5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['company', 'supplier'], name='expenses_su_company_ab457e_idx'),
        ),
    ]
