# Generated by Django 5.2.7 on 2026-03-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_alter_bill_options_alter_cheque_options_and_more'),
        ('inventory', '0012_remove_inventorylocation_uniq_location_per_store_and_more'),
        ('tenancy', '0010_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='creditcardcredit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='paydowncredit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='supplierrefund',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
    ]
