# Generated by Django 5.2.7 on 2025-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tax_category',
            field=models.CharField(blank=True, choices=[('Capital deductions', 'Capital deductions'), ('Allowable deduction', 'Allowable deduction'), ('Non Allowable deduction', 'Non Allowable deduction')], max_length=50, null=True),
        ),
    ]
