# Generated by Django 5.2.7 on 2025-11-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_tax_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalline',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalLine',
        ),
    ]
