# Generated by Django 5.2.7 on 2025-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_journalline_entry_remove_journalline_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('NON_CURRENT_ASSET', 'Non current assets'), ('CURRENT_ASSET', 'Current Assets'), ('OWNER_EQUITY', "Owner's Equity"), ('NON_CURRENT_LIABILITY', 'Non Current Liabilities'), ('CURRENT_LIABILITY', 'Current Liabilities'), ('OPERATING_INCOME', 'Operating Income'), ('INVESTING_INCOME', 'Investing Income'), ('OPERATING_EXPENSE', 'Operating Expense'), ('INVESTING_EXPENSE', 'Investing Expense'), ('FINANCING_EXPENSE', 'Financing Expense'), ('INCOME_TAX_EXPENSE', 'Income taxes')], max_length=50, null=True),
        ),
    ]
