# Generated by Django 5.2.7 on 2025-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journalentry_journalline'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
