# Generated by Django 5.2.7 on 2025-11-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_journalentry_source_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='source_app',
        ),
    ]
