# Generated by Django 5.2.7 on 2025-12-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_audittrail_new_data_alter_audittrail_old_data'),
        ('sowaf', '0008_remove_newsupplier_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_lines', to='sowaf.newcustomer'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_lines', to='sowaf.newsupplier'),
        ),
    ]
