# Generated by Django 5.2.7 on 2026-02-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
