# Generated by Django 5.2.7 on 2026-03-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_audittrail'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='tenancy.company'),
        ),
    ]
