# Generated by Django 5.2.7 on 2026-03-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_company_journalentry_company_and_more'),
        ('sowaf', '0016_delete_client'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='company',
        ),
        migrations.AddField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tenancy.company',
            ),
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tenancy.company',
            ),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tenancy.company',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together={('company', 'user', 'table_name')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='accounts_ac_company_17570f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='accounts_ac_company_daa212_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_number'], name='accounts_ac_company_2e1ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['timestamp'], name='accounts_au_timesta_c372e0_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_au_user_id_5395df_idx'),
        ),
        migrations.AddIndex(
            model_name='columnpreference',
            index=models.Index(fields=['company', 'user', 'table_name'], name='accounts_co_company_a5b7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date'], name='accounts_jo_company_6f6aca_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='accounts_jo_company_dc6a31_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entry', 'account'], name='accounts_jo_entry_i_8dd787_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(
                condition=models.Q(('account_number__isnull', False)),
                fields=('company', 'account_number'),
                name='uniq_account_number_per_company',
            ),
        ),
    ]