# Generated by Django 5.2.7 on 2026-03-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_columnpreference_unique_together_and_more'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='tenancy.company',
            ),
        ),
        migrations.AlterField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='tenancy.company',
            ),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='tenancy.company',
            ),
        ),
    ]