# Generated by Django 5.2.7 on 2026-03-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_company_alter_columnpreference_company_and_more'),
        ('tenancy', '0012_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company (tenant) for this audit log entry. Null for system/global events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='tenancy.company'),
        ),
    ]
