# Generated by Django 5.2.7 on 2026-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_companyinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvite',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
