# Generated by Django 5.2.7 on 2026-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_alter_companyinvite_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinvite',
            old_name='used_at',
            new_name='opened_at',
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='token',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
