# Generated by Django 5.2.7 on 2026-03-02 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_rename_used_at_companyinvite_opened_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinvite',
            old_name='opened_at',
            new_name='used_at',
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
