# Generated by Django 5.2.7 on 2026-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_kind',
            field=models.CharField(choices=[('SOWA', 'Sowa'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
