# Generated by Django 5.2.7 on 2026-03-19 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_kind',
            field=models.CharField(choices=[('SOWA', 'Sowa'), ('CLIENT', 'Client')], db_index=True, default='CLIENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_kind', 'is_active'], name='tenancy_com_company_30cc20_idx'),
        ),
    ]
