# Generated by Django 5.2.7 on 2026-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_alter_company_options_alter_company_company_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='tenancy_com_company_30cc20_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_kind',
            field=models.CharField(choices=[('SOWA', 'Sowa'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
