# Generated by Django 5.2.7 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_locked',
            field=models.BooleanField(default=False),
        ),
    ]
