# Generated by Django 5.2.7 on 2026-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_company_currency_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
