# Generated by Django 5.2.7 on 2025-11-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Cost of Sales'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_products', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Income'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_products', to='accounts.account'),
        ),
    ]
