# Generated by Django 5.2.7 on 2026-01-07 14:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('inventory', '0002_alter_product_expense_account_and_more'),
        ('sowaf', '0010_newcustomer_ar_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cost of Goods Sold account for Inventory items.', limit_choices_to={'account_type__in': ['OPERATING_EXPENSE', 'INVESTING_EXPENSE', 'FINANCING_EXPENSE', 'INCOME_TAX_EXPENSE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_products', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_asset_account',
            field=models.ForeignKey(blank=True, help_text='Where inventory value sits (Inventory Asset). Only needed for Inventory items.', limit_choices_to={'account_type': 'CURRENT_ASSET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['OPERATING_EXPENSE', 'INVESTING_EXPENSE', 'FINANCING_EXPENSE', 'INCOME_TAX_EXPENSE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_products', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['OPERATING_INCOME', 'INVESTING_INCOME']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_products', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sowaf.newsupplier'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('qty_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source_type', models.CharField(blank=True, choices=[('SALES_RECEIPT', 'Sales Receipt'), ('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('CHEQUE', 'Cheque'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=30, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
