# Generated by Django 5.2.7 on 2026-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_avg_cost_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pclass',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
