# Generated by Django 5.2.7 on 2026-02-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('inventory', '0006_alter_category_category_type_alter_pclass_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_asset_account',
            field=models.ForeignKey(blank=True, help_text='Where inventory value sits (Inventory Asset). Only needed for Inventory items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='accounts.account'),
        ),
    ]
