# Generated by Django 5.2.7 on 2026-02-17 23:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_inventory_asset_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='qty_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='source_type',
            field=models.CharField(blank=True, choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Stock')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorylocation'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'location', 'date'], name='inventory_i_product_9a9fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['source_type', 'source_id'], name='inventory_i_source__3135ed_idx'),
        ),
    ]
