# Generated by Django 5.2.7 on 2026-02-18 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorylocation_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylocation',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='qty_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
