# Generated by Django 5.2.7 on 2026-02-19 06:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransfer_stocktransferline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Store', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.mainstore'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_location_per_store'),
        ),
    ]
