# Generated by Django 5.2.7 on 2026-03-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_company_alter_columnpreference_company_and_more'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
        ('sowaf', '0016_delete_client'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorylocation',
            name='uniq_location_per_store',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_product_9a9fe5_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_source__3135ed_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainstore',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pclass',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainstore',
            name='name',
            field=models.CharField(default='Main Store', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pclass'),
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['bundle', 'product'], name='inventory_b_bundle__b84412_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'category_type'], name='inventory_c_company_647578_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['company', 'is_active'], name='inventory_i_company_e5ac14_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['company', 'store'], name='inventory_i_company_b36b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'product', 'location', 'date'], name='inventory_i_company_9e9267_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='inventory_i_company_b10588_idx'),
        ),
        migrations.AddIndex(
            model_name='mainstore',
            index=models.Index(fields=['company', 'is_active'], name='inventory_m_company_6bde4b_idx'),
        ),
        migrations.AddIndex(
            model_name='pclass',
            index=models.Index(fields=['company', 'class_name'], name='inventory_p_company_6e544d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'name'], name='inventory_p_company_9c5d59_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'type'], name='inventory_p_company_a6f033_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['company', 'transfer_date'], name='inventory_s_company_c6829b_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(fields=('company', 'store', 'name'), name='uniq_location_per_company_store'),
        ),
        migrations.AddConstraint(
            model_name='mainstore',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_store_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('company', 'sku'), name='uniq_product_sku_per_company'),
        ),
    ]
