# Generated by Django 5.2.7 on 2026-03-31 19:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audittrail_company'),
        ('inventory', '0013_alter_category_company_and_more'),
        ('tenancy', '0012_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='source_type',
            field=models.CharField(blank=True, choices=[('INVOICE', 'Invoice'), ('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Stock'), ('SALES_RECEIPT', 'Sales Receipt'), ('ASSEMBLY', 'Assembly Build')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='How many units of the finished product to build.', max_digits=12)),
                ('build_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('finished_product', models.ForeignKey(help_text='The product being assembled.', on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_finished', to='inventory.product')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_source', to='accounts.journalentry')),
            ],
            options={
                'ordering': ['-build_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BuildLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of this component needed per unit of the finished product.', max_digits=12)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.build')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_builds', to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['company', 'build_date'], name='inventory_b_company_6a2cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['company', 'status'], name='inventory_b_company_16eab7_idx'),
        ),
        migrations.AddIndex(
            model_name='buildline',
            index=models.Index(fields=['build', 'component'], name='inventory_b_build_i_610630_idx'),
        ),
    ]
