# Generated by Django 5.2.7 on 2026-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audittrail_company'),
        ('inventory', '0014_alter_inventorymovement_source_type_build_buildline_and_more'),
        ('sowaf', '0018_alter_newasset_company_alter_newcustomer_company_and_more'),
        ('tenancy', '0012_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_sku_per_company',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False), models.Q(('sku', ''), _negated=True)), fields=('company', 'sku'), name='uniq_product_sku_per_company'),
        ),
    ]
