# Generated by Django 5.2.7 on 2026-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_product_uniq_product_sku_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='When checked, an Inventory Asset account is created in the COA and stock is tracked.'),
        ),
    ]
