# Generated by Django 6.0.4 on 2026-04-26 12:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_track_inventory'),
        ('tenancy', '0014_company_original_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original purchased / received quantity', max_digits=12)),
                ('qty_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Units still available to be issued', max_digits=12)),
                ('date_created', models.DateField(default=django.utils.timezone.localdate, help_text='Date the layer was created (purchase / receipt date)')),
                ('is_exhausted', models.BooleanField(default=False, help_text='True when qty_remaining reaches zero')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_layers', to='inventory.product')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifo_layer', to='inventory.inventorymovement')),
            ],
            options={
                'ordering': ['date_created', 'id'],
                'indexes': [models.Index(fields=['company', 'product', 'date_created'], name='inventory_i_company_ba2e06_idx'), models.Index(fields=['company', 'product', 'is_exhausted'], name='inventory_i_company_f58155_idx')],
            },
        ),
    ]
