# Generated by Django 5.2.7 on 2026-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_add_inventory_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_opening_balance',
            field=models.BooleanField(default=False, help_text='True when this movement was created as a cut-off opening balance.'),
        ),
        migrations.AddField(
            model_name='product',
            name='cut_off_date',
            field=models.DateField(blank=True, help_text='Date from which FIFO was reset. Movements before this date are historical only.', null=True),
        ),
    ]
