# Generated by Django 6.0.4 on 2026-04-27 00:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_opening_balance_and_cutoff_fields'),
        ('sowaf', '0018_alter_newasset_company_alter_newcustomer_company_and_more'),
        ('tenancy', '0014_company_original_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft'), ('write_off', 'Write-off'), ('donation', 'Donation'), ('shrinkage', 'Shrinkage'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_increase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_decrease', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockCountWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='count_worksheets', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['-count_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.product')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcountworksheet')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('purchase_qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('source_document', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used_up', 'Used Up')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.inventorylocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
                'indexes': [models.Index(fields=['company', 'product'], name='inventory_b_company_28fff0_idx'), models.Index(fields=['company', 'status'], name='inventory_b_company_f5b733_idx'), models.Index(fields=['company', 'expiry_date'], name='inventory_b_company_873ff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiry_soon', 'Expiry Soon'), ('no_cost', 'No Cost'), ('no_sku', 'No SKU')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'alert_type'], name='inventory_i_company_fdfc76_idx'), models.Index(fields=['company', 'resolved_at'], name='inventory_i_company_faefba_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12)),
                ('expiry_warning_days', models.IntegerField(default=30)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_threshold', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'product'], name='inventory_i_company_51093b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['company', 'date'], name='inventory_s_company_00c902_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_9611ff_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountworksheet',
            index=models.Index(fields=['company', 'count_date'], name='inventory_s_company_728367_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountworksheet',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_496e45_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricehistory',
            index=models.Index(fields=['company', 'product', 'supplier'], name='inventory_s_company_7f09cb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricehistory',
            index=models.Index(fields=['company', 'date'], name='inventory_s_company_eb589c_idx'),
        ),
    ]
