# Generated by Django 5.2.7 on 2026-04-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audittrail_company'),
        ('inventory', '0021_stockadjustment_stockadjustmentline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='gl_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry that generated this movement (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='is_gl_posted',
            field=models.BooleanField(default=False, help_text='True when a GL journal entry has been created for this movement (prevents double-posting).'),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_stock_date',
            field=models.DateField(blank=True, help_text='Cut-off date for opening stock GL posting to Opening Balance Equity.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_stock_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total value of opening stock (for reporting and GL posting).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('FIFO', 'FIFO (First In, First Out)'), ('WEIGHTED_AVERAGE', 'Weighted Average')], default='FIFO', help_text='Inventory costing method. FIFO is the default and currently the only active method.', max_length=20),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, help_text='GL journal entry created when this adjustment was posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_source', to='accounts.journalentry'),
        ),
    ]
