# Generated by Django 6.0.4 on 2026-04-30 00:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audittrail_company'),
        ('inventory', '0022_gl_audit_fields'),
        ('tenancy', '0014_company_original_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of this component needed per ONE unit of the finished product.', max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cost snapshot at time of BOM creation.', max_digits=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='assembly_number',
            field=models.CharField(blank=True, help_text='Auto-generated assembly reference number.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where components are consumed and FG is received.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_builds', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='build',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total component cost captured at completion time.', max_digits=14),
        ),
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='build',
            name='wip_journal_entry',
            field=models.OneToOneField(blank=True, help_text='Journal entry for Step 1: DR WIP / CR Raw Materials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_wip_source', to='accounts.journalentry'),
        ),
        migrations.AlterField(
            model_name='build',
            name='journal_entry',
            field=models.OneToOneField(blank=True, help_text='Journal entry for Step 2: DR Finished Goods / CR WIP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_source', to='accounts.journalentry'),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending (Legacy)')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='BOM version number.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active BOM per product.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('finished_product', models.ForeignKey(help_text='The product that this BOM produces.', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product')),
            ],
            options={
                'ordering': ['-is_active', '-version'],
            },
        ),
        migrations.AddField(
            model_name='build',
            name='bom',
            field=models.ForeignKey(blank=True, help_text='Source BOM (optional; components may be entered manually).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='inventory.billofmaterials'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['company', 'assembly_number'], name='inventory_b_company_3ddca8_idx'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.billofmaterials'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='component_item',
            field=models.ForeignKey(help_text='The raw material / component.', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['company', 'finished_product'], name='inventory_b_company_4f31fa_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['company', 'is_active'], name='inventory_b_company_1f66c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('company', 'finished_product', 'version'), name='uniq_bom_version_per_product'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['bom', 'component_item'], name='inventory_b_bom_id_7b4eac_idx'),
        ),
    ]
