# Generated by Django 5.2.7 on 2026-03-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaAuth', '0003_staffinvite_staffloginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
    ]
