# Generated by Django 5.2.7 on 2026-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaAuth', '0004_newuser_can_manage_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
