# Generated by Django 5.2.7 on 2025-11-14 10:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('sowaf', '0004_newsupplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('statement_type', models.CharField(choices=[('transaction', 'Transaction Statement'), ('open_item', 'Open Item'), ('balance_forward', 'Balance Forward')], default='transaction', max_length=32)),
                ('email_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='sowaf.newcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('sales_receipt', 'Sales Receipt'), ('balance_forward', 'Balance Forward')], max_length=32)),
                ('ref_no', models.CharField(blank=True, max_length=64)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.statement')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
