# Generated by Django 5.2.7 on 2025-11-14 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_statement_statementline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementline',
            name='running_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, null=True),
        ),
    ]
