# Generated by Django 5.2.7 on 2025-11-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_statementline_running_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='sales.salesreceipt'),
        ),
    ]
