# Generated by Django 5.2.7 on 2025-11-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_journalentry_source_app'),
        ('sales', '0005_alter_salesreceipt_deposit_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='deposit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_receipts', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='salesreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesreceipt'),
        ),
    ]
