# Generated by Django 5.2.7 on 2025-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesreceipt_deposit_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
