# Generated by Django 5.2.7 on 2025-12-31 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_newinvoice_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOpenBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_balance_line', to='sales.payment')),
            ],
        ),
    ]
