# Generated by Django 5.2.7 on 2026-01-02 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_paymentopenbalanceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='unapplied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
