# Generated by Django 5.2.7 on 2026-01-02 16:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('sales', '0009_payment_amount_received_payment_unapplied_amount'),
        ('sowaf', '0010_newcustomer_ar_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sowaf.newcustomer')),
                ('paid_from', models.ForeignKey(limit_choices_to={'account_type__in': ['Bank', 'Cash and Cash Equivalents']}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_refund_account', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('received_to', models.ForeignKey(limit_choices_to={'account_type__in': ['Bank', 'Cash and Cash Equivalents']}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refund_account', to='accounts.account')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sowaf.newsupplier')),
            ],
        ),
    ]
