# Generated by Django 5.2.7 on 2026-02-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_journalline_customer_journalline_supplier'),
        ('sales', '0012_columnpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_source', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
