# Generated by Django 5.2.7 on 2026-02-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_newinvoice_is_posted_newinvoice_journal_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newinvoice',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='posted_at',
        ),
    ]
