# Generated by Django 5.2.7 on 2026-02-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_inventory_asset_account'),
        ('sales', '0014_remove_newinvoice_is_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
    ]
