# Generated by Django 5.2.7 on 2026-02-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
        ('sales', '0015_alter_newinvoice_class_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.inventorylocation'),
        ),
    ]
