# Generated by Django 5.2.7 on 2026-03-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_newinvoice_location'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_company_invoices', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_receipts', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='statement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_statements', to='tenancy.company'),
        ),
    ]
