# Generated by Django 5.2.7 on 2026-03-04 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_company_alter_columnpreference_company_and_more'),
        ('inventory', '0011_mainstore_alter_inventorylocation_is_active_and_more'),
        ('sales', '0017_newinvoice_company_payment_company_and_more'),
        ('sowaf', '0016_delete_client'),
        ('tenancy', '0008_rename_opened_at_companyinvite_used_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newinvoice',
            options={'ordering': ['-date_created', '-id']},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-statement_date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='paid_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_refund_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierrefund',
            name='received_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refund_account', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='columnpreference',
            unique_together={('company', 'user', 'table_name')},
        ),
        migrations.AddIndex(
            model_name='columnpreference',
            index=models.Index(fields=['company', 'user', 'table_name'], name='sales_colum_company_795473_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrefund',
            index=models.Index(fields=['company', 'refund_date'], name='sales_custo_company_f3ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrefund',
            index=models.Index(fields=['company', 'customer'], name='sales_custo_company_5bde5d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product'], name='sales_invoi_invoice_966e68_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['company', 'date_created'], name='sales_newin_company_472063_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['company', 'due_date'], name='sales_newin_company_cbb99a_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['company', 'customer'], name='sales_newin_company_42a902_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='sales_payme_company_55f8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'customer'], name='sales_payme_company_dabdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['payment', 'invoice'], name='sales_payme_payment_c5d1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringgeneratedinvoice',
            index=models.Index(fields=['recurring', 'run_date'], name='sales_recur_recurri_00e0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['company', 'is_active', 'next_run_date'], name='sales_recur_company_e1a0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['company', 'customer'], name='sales_recur_company_e29d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreceipt',
            index=models.Index(fields=['company', 'receipt_date'], name='sales_sales_company_4c8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreceipt',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_d37cce_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreceiptline',
            index=models.Index(fields=['receipt', 'product'], name='sales_sales_receipt_5d3560_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['company', 'statement_date'], name='sales_state_company_ce04f2_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['company', 'customer'], name='sales_state_company_481e54_idx'),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['statement', 'date'], name='sales_state_stateme_368971_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['company', 'refund_date'], name='sales_suppl_company_ec5536_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['company', 'supplier'], name='sales_suppl_company_08789a_idx'),
        ),
    ]
