# Generated by Django 5.2.7 on 2026-03-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_newinvoice_options_alter_statement_options_and_more'),
        ('tenancy', '0010_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnpreference',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='supplierrefund',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company'),
        ),
    ]
