# Generated by Django 5.2.7 on 2026-03-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_audittrail_company'),
        ('sales', '0019_alter_columnpreference_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_source', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_receipt_source', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
